doctorsapp/views.py
from google_auth_oauthlib.flow import InstalledAppFlow
from google.oauth2.credentials import Credentials
from flask import request, render_template, flash, url_for, redirect, Blueprint, jsonify, session
from .forms import *
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from .user import User
from flask_mail import Message
from .extensions import db, mail
from .models import *
from sqlalchemy import and_

import string, secrets, os, json

main = Blueprint('main', __name__)
# company email for gmail password
company_email = "johny.achkar02@gmail.com"
email_content = "Dear User, this is your token to reset your password. Kindly reset within 2 minutes before it gets expired"
email_subject = "Password Change"
GMAIL_SCOPES = ['https://www.googleapis.com/auth/gmail.compose']


def get_gmail_credential():
    creds = None
    current_script_path = os.path.abspath(__file__)
    current_script_directory = os.path.dirname(current_script_path)
    resources = os.path.join(current_script_directory, "resources")
    credentials_file = f"{resources}/json_file.json"
    # token.json should be created when you run the function
    if os.path.exists('token.json'):
        with open('token.json', 'r') as token_file:
            credentials_data = token_file.read()
            creds = Credentials.from_authorized_user_info(json.loads(credentials_data))

    if not creds or not creds.valid:
        flow = InstalledAppFlow.from_client_secrets_file(credentials_file, GMAIL_SCOPES)
        creds = flow.run_local_server(port=0)

        with open('token.json', 'w') as token_file:
            token_file.write(creds.to_json())
    return creds


@main.route('/', methods=['POST', 'GET'])
def home():
    form = UserForm()
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        doctor = Doctors.query.filter_by(email=email).first()
        secretary = Secretaries.query.filter_by(email=email).first()
        admin = Admin.query.filter_by(email=email).first()

        if doctor is not None:
            doctor_password = doctor.hashed_password
            if check_password_hash(doctor_password, password) and (doctor.status == "active"):
                login_user(User('doctor', doctor.id), remember=True)
                return redirect(url_for('main.features'))

        elif secretary is not None:
            secretary_password = secretary.hashed_password
            if check_password_hash(secretary_password, password) and (secretary.status == "active"):
                login_user(User('secretary', secretary.id), remember=True)
                return redirect(url_for('main.features'))

        elif admin is not None:
            admin_password = admin.hashed_password
            if check_password_hash(admin_password, password) and (admin.status == "active"):
                login_user(User('admin', admin.id), remember=True)
                return redirect(url_for('main.admin_dashboard'))
        else:
            flash("Your credentials are incorrect !")
            return redirect(url_for('main.home'))

    return render_template("index.html", form=form)


@main.route('/features', methods=['GET', 'POST'])
def features():
    return render_template("features.html")


@main.route('/register_patient', methods=['GET', 'POST'])
def register_patient():
    form = registrationForm()
    if request.method == 'POST':
        name = request.form.get('name')
        name = name.capitalize()
        father = request.form.get('father')
        father = father.capitalize()
        family = request.form.get('family')
        family = family.capitalize()
        dob = request.form.get('dob')
        print("the dob is ", dob)
        gender = request.form.get('gender')
        phone = request.form.get('phone')
        email = request.form.get('email')
        city = request.form.get('city')
        registration = patientRegistrationInfo.query.filter(
            and_(
                patientRegistrationInfo.email == email,
                patientRegistrationInfo.phone == phone
            )
        ).first()
        if not registration:
            new_registration = patientRegistrationInfo(
                name=name,
                father=father,
                family=family,
                dob=dob,
                gender=gender,
                phone=phone,
                email=email,
                city=city,
                registered_by_who=current_user.get_id()
            )
            db.session.add(new_registration)
            db.session.commit()
            return redirect(url_for('main.book_appointment'))
        else:
            return redirect(url_for('main.book_appointment'))

    return render_template("register_patient.html", form=form)


@main.route('/book_appointment', methods=['GET', 'POST'])
def book_appointment():
    if request.method == 'POST':
        name = request.form.get('first-name')
        name = name.capitalize()
        family = request.form.get('family-name')
        family = family.capitalize()
        father = request.form.get('fathers')
        phone = request.form.get('phone')
        freeText = request.form.get('free-text')
        date = request.form.get('date')
        start_time = request.form.get('start-time')

        hidden_start_time = request.form.get('hidden-start')

        hidden_end_time = request.form.get('hidden-end')

        end_time = request.form.get('end-time')
        appointment_type = request.form.get('select-appointment')
        treating_physician = request.form.get('select-physician')
        procedure_type = request.form.get('select-procedure')
        chief_complaint = request.form.get('select-chief')
        booking_confirmation = request.form.get('booking_reminder')
        appointment_confirmation = request.form.get('appointment_reminder')
        weather = request.form.get('weather_reminder')
        traffic = request.form.get('traffic_reminder')
        prior_proc_reminder = request.form.get('prior_procedure_reminder')
        post_proc_reminder = request.form.get('post_procedure_reminder')

        doctor_instance = Doctors.query.filter_by(email=treating_physician).first()
        doctor_name = doctor_instance.name
        doctor_family = doctor_instance.family
        fullDoctorName = doctor_name + "" + doctor_family

        # get the dob of the patient and other params
        dob_instance = patientRegistrationInfo.query.filter(
            and_(
                phone == phone,
                name == name,
            )
        ).first()
        dob_attr = dob_instance.dob.strftime("%Y-%m-%d")
        patient_dob_formated = datetime.strptime(dob_attr, "%Y-%m-%d").strftime("%d %B %Y")
        session['dob'] = patient_dob_formated

        session['patientName'] = name
        session['familyName'] = family
        session['phone'] = phone

        new_encounter = bookingEncounter(
            date=date,
            start_time=start_time,
            end_time=end_time,
            patient_name=name,
            patient_family_name=family,
            patient_fathers_name=father,
            phone=phone,
            appointment_type=appointment_type,
            procedure_type=procedure_type,
            treating_physician=treating_physician,
            chief_complaint=chief_complaint,
            bookingConfirmation=booking_confirmation,
            appointmentReminder=appointment_confirmation,
            weatherReminder=weather,
            trafficReminder=traffic,
            priorProcedureInstructions=prior_proc_reminder,
            postProcedureInstructions=post_proc_reminder
        )
        db.session.add(new_encounter)
        db.session.commit()

        encounter_id = new_encounter.id

        response = {
            'start_time': hidden_start_time,
            'end_time': hidden_end_time,
            'patient_name': name,
            'family_name': family,
            'encounter_id': encounter_id,
            'encounter_id_a': str(encounter_id) + '-' + 'a',
            'encounter_id_b': str(encounter_id) + '-' + 'b',
            'encounter_id_c': str(encounter_id) + '-' + 'c',
            'phone': phone,
            'appointment': appointment_type,
            'treating_physician': fullDoctorName,
            'free_text': freeText

        }
        return jsonify(response)

    return render_template("book_appointment.html")


@main.route('/resize_appointment', methods=['GET', 'POST'])
def resize_appointment():
    if request.method == 'POST':
        date = request.form.get('date-edit')
        name = request.form.get('first-name-edit')
        family = request.form.get('family-name-edit')
        eventID = request.form.get('event_id')
        start_time = request.form.get('start-time-edit')
        phone = request.form.get('phone-edit')
        end_time = request.form.get('end-time-edit')
        constructed_start_time = date + "T" + start_time + ":00+03:00"
        constructed_end_time = date + "T" + end_time + ":00+03:00"
        appointment_type = request.form.get('select-appointment-resize')
        booking_confirmation = request.form.get('booking_reminder')
        appointment_confirmation = request.form.get('appointment_reminder')
        weather = request.form.get('weather_reminder')
        traffic = request.form.get('traffic_reminder')
        prior_proc_reminder = request.form.get('prior_procedure_reminder')
        post_proc_reminder = request.form.get('post_procedure_reminder')
        event_encounter = bookingEncounter.query.filter_by(id=eventID).first()
        if event_encounter:
            event_encounter.date = date,
            event_encounter.start_time = start_time,
            event_encounter.end_time = end_time,
            event_encounter.bookingConfirmation = booking_confirmation,
            event_encounter.appointmentReminder = appointment_confirmation,

doctorsapp/templates/add_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

</head>
<body>
{% include "bootstrap.html" %}
<div class="container" style="text-align: center; margin-bottom: 20px; margin-top: 10px">
    <h3>Enter Admin Data</h3>

    {% with messages=get_flashed_messages() %}
    <div class="container" style="text-align: center">
        {% for message in messages %}
        <div class="alert alert-warning">{{ message }}</div>
        {% endfor %}
    </div>
    {% endwith %}
</div>
<div class="container-fluid index-container">
    <div class="row">
        <div class="col">
            <form method="POST">
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Name" name="name" autocomplete="off" required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Family" name="family" autocomplete="off"
                           required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="email" placeholder="Email" name="email" autocomplete="off"
                           required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Password" name="password" autocomplete="off"
                           required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" value="admin" name="type" readonly required>
                </div>
                <div class="form-group">
                    <select class="form-control add-doctors-margin" name="status" required>
                        <option value="" disabled selected>Select Status ...</option>
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class=" btn btn-primary" id="save-button">Save</button>
                </div>
            </form>

        </div>
    </div>
</div>

</body>
</html>

doctorsapp/templates/add_assistant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

</head>
<body>
{% include "bootstrap.html" %}

<div class="container" style="text-align: center; margin-bottom: 20px; margin-top: 10px">
    <h3>Enter Assistant Data</h3>

    {% with messages=get_flashed_messages() %}
    <div class="container" style="text-align: center">
        {% for message in messages %}
        <div class="alert alert-warning">{{ message }}</div>
        {% endfor %}
    </div>
    {% endwith %}
</div>
<div class="container-fluid index-container">
    <div class="row">
        <div class="col">
            <form method="POST">
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Name" name="name" autocomplete="off"  required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Family" name="family" autocomplete="off"  required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Father" name="father" autocomplete="off"  required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="phone" name="phone" autocomplete="off"  required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="email" placeholder="Email" name="email" autocomplete="off"  required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Password" name="password" autocomplete="off"  required>
                </div>
                     <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" value="secretary" name="type" readonly required>
                </div>

                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Doctor Email" name="doctor_email" autocomplete="off"  required>

                </div>
                <div class="form-group">
                    <select class="form-control add-doctors-margin" name="status" required>
                        <option value="" disabled selected>Select Status ...</option>
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class=" btn btn-primary" id="save-button">Save</button>
                </div>
            </form>

        </div>
    </div>
</div>

</body>
</html>

doctorsapp/templates/add_doctors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
{% include "bootstrap.html" %}

<div class="container" style="text-align: center; margin-bottom: 20px; margin-top: 10px">
    <h3>Enter Doctor's Data</h3>

    {% with messages=get_flashed_messages() %}
    <div class="container" style="text-align: center">
        {% for message in messages %}
        <div class="alert alert-warning">{{ message }}</div>
        {% endfor %}
    </div>
    {% endwith %}
</div>
<div class="container-fluid index-container">
    <div class="row">
        <div class="col">
            <form method="POST">
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Name" name="name" autocomplete="off" required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Family" name="family" autocomplete="off"
                           required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Father" name="father" autocomplete="off"
                           required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="phone" name="phone" autocomplete="off"
                           required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="email" placeholder="Email" name="email" autocomplete="off"
                           required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" placeholder="Password" name="password" autocomplete="off"
                           required>
                </div>
                <div class="form-group add-doctors-margin">
                    <input class="form-control " type="text" value="doctor" name="type" readonly
                           required>

                </div>
                <div class="form-group add-doctors-margin">
                    <select class="form-control " name="specialty" required>
                        <option value="" disabled selected>Select Specialty ...</option>
                        <option value="cardiology">Cardiology</option>
                        <option value="endocrinology">Endocrinology</option>
                        <option value="general_surgery">General Surgery</option>
                        <option value="dentistry">Dentistry</option>
                    </select>
                </div>
                <div class="form-group">
                    <select class="form-control add-doctors-margin" name="status" required>
                        <option value="" disabled selected>Select Status ...</option>
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class=" btn btn-primary" id="save-button">Save</button>
                </div>
            </form>

        </div>
    </div>
</div>

</body>
</html>

doctorsapp/templates/add_token.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{{ url_for('static', filename='styles.css') }}" rel="stylesheet">
    <script src="../static/add_token.js"></script>
</head>
<body class="add-token-image">
{% include "bootstrap.html" %}

<div class="container-fluid change-password-centered">
    <div class="row">
        <div class="col">
            <div class="form-group index-input1">
                <h3>Please Add you token here </h3>
            </div>
            <form method="POST">
                <div class="form-group index-input1">
                    <div class="position-relative">
                        {{form.password(placeholder='Add Token here ...',class='form-control password-input')}}
                        <button type="button" class="add-token-toggle" onclick="togglePassword()">
                            <i class="fas fa-eye" id="toggle-password"></i>
                        </button>
                    </div>
                </div>
                <div class="form-group text-center">
                    {{form.submit(class='btn btn-light',style='background-color:#fff8fb')}}
                </div>
            </form>
            <div>
                {% with messages = get_flashed_messages() %}
                {% for message in messages %}
                {{message}}
                {% endfor %}
                {% endwith %}
            </div>
        </div>
    </div>
</div>

</body>
</html>

doctorsapp/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

</head>
<body>
{% include "bootstrap.html" %}

<div class="container-fluid index-form container-margin ">
  <div class="row">
    <div class="col">
      <h3>Admin Dashboard</h3>
    </div>
  </div>
  <div class="row">
    <a class="deactivate_user_but index-input1 text-center" href="{{url_for('main.add_doctors')}}">Add Doctor</a>
    <a class="deactivate_user_but index-input1 text-center" href="{{url_for('main.add_assistant')}}">Add Assistant</a>
    <a class="deactivate_user_but text-center" href="{{url_for('main.deactivate_user')}}">Deactivate User</a>
  </div>
</div>

</body>
</html>

doctorsapp/templates/bootstrap.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#    <script src="https://code.jquery.com/jquery-3.7.1.min.js"#}
{#            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>#}
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>#}
{#    <script src="https://kit.fontawesome.com/442f99fa38.js" crossorigin="anonymous"></script>#}
{##}
{##}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
{#    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
<script src="https://kit.fontawesome.com/442f99fa38.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

doctorsapp/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

</head>
<body class="change_password_img">
{% include "bootstrap.html" %}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">
                <form method="POST" class="change-password-centered">
                    <div class="index-input1">
                        <h3>A token will be sent to your email</h3>
                    </div>
                    <div class="form-group index-input1">
                        {{form.email(class="form-control",placeholder='Add your email ...',value='')}}
                    </div>
                    <div class="form-group">
                        {{form.submit(class="form-control")}}
                    </div>
                    <div>
                        {% with messages = get_flashed_messages() %}
                        {% for message in messages %}
                        {{message}}
                        {% endfor %}
                        {% endwith %}
                    </div>
                </form>
        </div>
    </div>
</div>

</body>
</html>

doctorsapp/templates/deactivate_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

</head>
<body>
{% include "bootstrap.html" %}
<div class="container-fluid index-form index-input1 container-margin ">
    <div class="row">
        <div class="col">
            <h3>Activate / Deactivate User</h3>
        </div>
    </div>
</div>

<div class="container-fluid index-form">
    <div class="row">
        <div class="col">
            <form method="POST">
                <div class="form-group add-doctors-margin">
                    <input type="email" class="form-control" name="email" autocomplete="off"
                           placeholder="User Email ..."
                           required>
                </div>
                <div class="form-group">
                    <select class="form-control add-doctors-margin" name="status" required>
                        <option value="" disabled selected>Change Status ...</option>
                        <option value="active">Active</option>
                        <option value="Inactive">Inactive</option>
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-light">Save</button>

                </div>

                <div class="container-margin">
                    <a class="deactivate_user_but" href="{{url_for('main.add_doctors')}}">Add New Doctor</a>
                    <a class="deactivate_user_but" href="{{url_for('main.add_assistant')}}">Add New Assistant</a>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container index-form">
    <div class="row">
        <div class="col">
            {% with messages = get_flashed_messages() %}
            {% for message in messages %}
            <div class="alert alert-warning">{{message}}</div>
            {% endfor %}
            {% endwith %}
        </div>
    </div>

</div>

</body>
</html>

doctorsapp/templates/features.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="../static/styles.css" rel="stylesheet">
</head>
<body class="features-back-image">
{% include "navbar.html" %}


</body>
</html>

doctorsapp/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='styles.css') }}">
</head>
<body>
{% include "bootstrap.html" %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a style="margin-right: 30px;color: orange;font-weight: bold" class="navbar-brand" href="#">SolvIT</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown" style="margin-right: 20px">
                    <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Appointment
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('main.register_patient') }}">Register a patient</a></li>

                        <li><a class="dropdown-item" href="#">Book an appointment</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Reschedule an appointment</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown" style="margin-right: 20px">
                    <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Reports
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Medical Report</a></li>
                        <li><a class="dropdown-item" href="#">Sick Leave</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Prescription</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown" style="margin-right: 20px">
                    <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Instructions & Reminders
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">General Reminders</a></li>
                        <li><a class="dropdown-item" href="#">Prior to Procedure</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Post Procedure</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown" style="margin-right: 20px">
                    <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Finances
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Bill a patient</a></li>
                        <li><a class="dropdown-item" href="#">Place orders</a></li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Stock Management</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Financial Dashboard</a></li>

                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Tele-Consultation</a>
                </li>

            </ul>
        </div>
    </div>
</nav>
</body>
</html>